version: "3.8"

services:
  app:
    build:
      context: .
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    command: bash -c "php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - 8000:8000
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
