version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    # command: bash -c "composer create-project --prefer-dist laravel/laravel ."
    command: bash -c "php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - 8000:8000

  # Banco de dados (opcional)
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
